packages:
 - packages/*

catalog:
    "@egoist/tailwindcss-icons": "^1.8.2"
    "@headlessui/react": "^2.2.0"
    "@headlessui/tailwindcss": "^0.2.1"
    "@js-temporal/polyfill": "^0.4.4"
    "@tailwindcss/forms": "^0.5.9"
    "@tailwindcss/typography": "^0.5.15"
    "@types/react": "^19.0.1"
    "@types/react-dom": "^19.0.2"
    "autoprefixer": "^10.4.20"
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "react-router": "^7.1.0-pre.0"
    "tailwindcss": "^3.4.17"
