#:schema node_modules/wrangler/config-schema.json
name = "furigana-maker"
workers_dev = true

compatibility_date = "2024-12-18"

[assets]
directory = "./build/client"

[build]
command = "pnpm run build"
